version: '3.7'

services:
  ethermintdnode0:
    container_name: ethermintdnode0
    image: "lekg1/ethermint"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
    environment:
      - ID=0
      - LOG=${LOG:-ethermintd.log}
    volumes:
      - ./init:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2
    entrypoint: "sh /ethermint/init.sh"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16